wth - RMID functionalities part 3
bmic-development/sparc-request pull request #13
Opened 2017-01-13 15:38 UTC by wtholt

Make AJAX request to RMID API to get short_title, long_title and pi_name
from entered RMID record. Fields are disabled upon successful request.
Implemented Gon gem to have access to our environment variables in our
assets. [#136746539]

2017-01-13 19:26 UTC, kyle-glick commented on app/views/protocols/form/_project_roles_fields.html.haml
> +          = pr_form.text_field :identity_id, placeholder: t(:constants)[:prompts][:search_for_user], class: 'form-control rm-id-dependent'
Needs to be added to the same partial in the dashboard
app/views/dashboard/protocols/form/_project_roles_fields.html.haml

2017-01-13 19:26 UTC, kyle-glick commented on app/views/protocols/form/study_form_sections/_study_information.html.haml
> +        = form.text_field :research_master_id, class: 'form-control research-master-field'
Ditto
app/views/dashboard/protocols/form/study_form_sections/_study_information.html.haml

2017-01-13 19:27 UTC, kayla-glick requested changes

2017-01-13 19:27 UTC, kyle-glick commented on app/views/protocols/form/_project_roles_fields.html.haml
> +          = pr_form.text_field :identity_id, placeholder: t(:constants)[:prompts][:search_for_user], class: 'form-control rm-id-dependent'
Needs to be added to the same partial in the dashboard
app/views/dashboard/protocols/form/_project_roles_fields.html.haml

2017-01-13 19:27 UTC, kyle-glick commented on app/views/protocols/form/study_form_sections/_study_information.html.haml
> +        = form.text_field :research_master_id, class: 'form-control research-master-field'
Ditto
app/views/dashboard/protocols/form/study_form_sections/_study_information.html.haml

2017-01-17 15:21 UTC, jleonardw9 approved these changes

2017-01-17 16:14 UTC, kayla-glick approved these changes

2017-01-19 14:42 UTC, merged