wth - (SPARCDashboard) Search All is not Including Projects
bmic-development/sparc-request pull request #156
Opened 2017-03-17 15:58 UTC by wtholt

It was failing to include Projects because it was trying to search for
attributes that do not belong to Projects (pro_number, hr#, rmid).
Revised the search all function to only search for shared attributes
between Projects & Studies. [#141901591]

2017-03-17 18:04 UTC, jleonardw9 approved these changes

2017-03-17 18:29 UTC, Stuart-Johnson approved these changes

2017-03-19 03:20 UTC, kayla-glick requested changes

2017-03-19 03:20 UTC, kyle-glick commented on app/models/protocol.rb
> +      all_query = [authorized_user_query, pi_query, protocol_id_query, title_query]
Wasn't this a requested feature, though? Can we look into whether there's another way we can still use these attributes?

2017-03-20 14:23 UTC, wtholt commented on app/models/protocol.rb
> +      all_query = [authorized_user_query, pi_query, protocol_id_query, title_query]
@kyle-glick Feel free to put a story in for that. I talked to Wenjun about this change and she said it made sense to go with this change.

2017-03-20 16:25 UTC, kayla-glick approved these changes

2017-03-20 16:25 UTC, kyle-glick commented on app/models/protocol.rb
> +      all_query = [authorized_user_query, pi_query, protocol_id_query, title_query]
Done and approved. https://www.pivotaltracker.com/story/show/142067617

2017-03-20 18:55 UTC, merged