Jl form functionality cleanup
bmic-development/sparc-request pull request #157
Opened 2017-03-17 16:00 UTC by jleonardw9

2017-03-17 17:10 UTC, wtholt approved these changes

2017-03-19 03:24 UTC, kayla-glick requested changes

2017-03-19 03:24 UTC, kyle-glick commented on app/helpers/additional_details/application_helper.rb
> +    DateTime.strptime(time.gsub(':', ''), '%H%M').strftime('%l:%M') + modifier
There should be a placeholder for AM/PM in DateTime.strptime. %p should do it

2017-03-19 03:24 UTC, kyle-glick commented on app/views/additional_details/submissions/_submission_info.html.haml
>                  = qr.content.delete('[]').delete('\"')
Can you add the gsub here as well?

2017-03-20 14:16 UTC, jleonardw9 commented on app/helpers/additional_details/application_helper.rb
> +    DateTime.strptime(time.gsub(':', ''), '%H%M').strftime('%l:%M') + modifier
I kind of like my modifier code, so I think I'm going to leave it in.

2017-03-20 14:30 UTC, jleonardw9 commented on app/views/additional_details/submissions/_submission_info.html.haml
>                  = qr.content.delete('[]').delete('\"')
That's Will's code and it's doing it's job, so I'm not going to mess with it.

2017-03-20 14:36 UTC, jwiel86 approved these changes

2017-03-20 15:18 UTC, kyle-glick commented on app/helpers/additional_details/application_helper.rb
> +    DateTime.strptime(time.gsub(':', ''), '%H%M').strftime('%l:%M') + modifier
Can you explain what the modifier is doing? I'm a bit confused about the '0' || '10' || '11' part

2017-03-20 15:21 UTC, jleonardw9 commented on app/helpers/additional_details/application_helper.rb
> +    DateTime.strptime(time.gsub(':', ''), '%H%M').strftime('%l:%M') + modifier
It's converting military time to regular time. So if a time string has either '0', '10', or '11' as the leading character's then it is in the morning. All else are PM.

2017-03-20 15:23 UTC, bmic-development commented
Time format is something like 02:01:01 or 11:21:23 or 23:13:13.  So it’s looking at if it start with 0 or first 2 numbers are 10,11 then it’s AM otherwise it’s PM.

From: kyle-glick <notifications@github.com>
Reply-To: bmic-development/sparc-request <reply@reply.github.com>
Date: Monday, March 20, 2017 at 11:18 AM
To: bmic-development/sparc-request <sparc-request@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [bmic-development/sparc-request] Jl form functionality cleanup (#157)




@kyle-glick commented on this pull request.

________________________________

In app/helpers/additional_details/application_helper.rb<https://github.com/bmic-development/sparc-request/pull/157#discussion_r106928595>:

> @@ -1,2 +1,9 @@

 module AdditionalDetails::ApplicationHelper

+

+  def convert_time(time)

+    modifier = ''

+    ((time.first == '0') || (time[0..1] == '10') || (time[0..1] == '11')) ? modifier = ' AM' : modifier = ' PM'

+

+    DateTime.strptime(time.gsub(':', ''), '%H%M').strftime('%l:%M') + modifier

Can you explain what the modifier is doing? I'm a bit confused about the '0' || '10' || '11' part

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/bmic-development/sparc-request/pull/157#discussion_r106928595>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ACeOUbiGAfq8fDkH1O4uomHExDXTXtrYks5rnpjMgaJpZM4Mgxrm>.




-------------------------------------------------------------------------
This message was secured via TLS by MUSC.

2017-03-20 15:58 UTC, kayla-glick requested changes

2017-03-20 15:58 UTC, kyle-glick commented on app/helpers/additional_details/application_helper.rb
> +    DateTime.strptime(time.gsub(':', ''), '%H%M').strftime('%l:%M') + modifier
You could use `DateTime.strptime(time, '%H:%M').strftime('%l:%M %p')` to do the same thing all in 1 line

2017-03-21 20:47 UTC, kyle-glick commented on app/views/additional_details/submissions/_submission_info.html.haml
>                  = qr.content.delete('[]').delete('\"')
It looks at though it's performing the same function as the checkbox gsub. @wtholt is that correct? If so, could we combine the checkbox and multiple_dropdown logic into one if statement
`if ['multiple_dropdown', 'checkbox'].include?(item.item_type)`

2017-03-27 14:51 UTC, amcates commented
@jleonardw9 I have to agree with Kyle.  Using the strptime method instead of custom code would be better in this case.

2017-03-27 15:06 UTC, jleonardw9 commented on app/helpers/additional_details/application_helper.rb
> +    DateTime.strptime(time.gsub(':', ''), '%H%M').strftime('%l:%M') + modifier
Totally missed this comment last week. Your suggestion worked great, should be up there now.

2017-03-27 15:11 UTC, jleonardw9 commented
Yeah, I agree as well. Just changed it.

2017-03-27 17:39 UTC, kayla-glick submitted a review, later dismissed

2017-03-27 17:39 UTC, kyle-glick commented on app/views/additional_details/submissions/_submission_info.html.haml
> +                = qr.content.gsub(/["\[\]]/, '')
I tested `qr.content.delete('[]').delete('\"')` and `qr.content.gsub(/["\[\]]/, '')` and they appear to be doing the same thing: Replacing/removing the characters []". We should combine this block and the if block into a single statement. 
`if ['checkbox', 'multiple_dropdown'].include?(qr.content)`
`  qr.content.delete('[]\"')` or `qr.content.gsub(/["\[\]]/, '')`

2017-03-27 17:53 UTC, amcates commented on app/views/additional_details/submissions/_submission_info.html.haml
> +                = qr.content.gsub(/["\[\]]/, '')
I would label that a refactor and make another pull request.  Not necessary to proceed.  In the same thought you could change 'qr.content.gsub' to another method call similar to convert_time.

2017-03-27 18:00 UTC, kyle-glick commented on app/views/additional_details/submissions/_submission_info.html.haml
> +                = qr.content.gsub(/["\[\]]/, '')
Fair enough.

2017-03-28 13:49 UTC, Stuart-Johnson approved these changes

2017-03-28 13:50 UTC, merged