wth - (SPARCDashboard) View Epic Queue Reconfigurations: Part 1
bmic-development/sparc-request pull request #159
Opened 2017-03-20 15:00 UTC by wtholt

1. When a user double clicks on a row, they are taken to the
Dashboard::Protocol#show for the associated Protocol.
2. Added 3 more columns, 'Current Queue Date' (epic_queues.created_at),
'By', (first and last name attributes in epic_queues.identity...this
association was also missing), and
'Send' (Protocols#push_to_epic).
3. Changed title of tab to 'Current'.
[#141707817]

2017-03-20 16:05 UTC, kayla-glick requested changes

2017-03-20 16:05 UTC, kyle-glick commented on app/helpers/dashboard/epic_queues_helper.rb
> +    "#{identity.try(:first_name)} #{identity.try(:last_name)}"
Identity already has #full_name which does this. So you could just return `epic_queue.identity.full_name`

2017-03-20 16:05 UTC, kyle-glick commented on app/views/dashboard/epic_queues/_epic_queue_list.html.haml
> +              Current Queue Date
Needs to be YMLized

2017-03-20 16:05 UTC, kyle-glick commented on app/views/dashboard/epic_queues/_epic_queue_list.html.haml
> +              by
Ditto

2017-03-20 16:05 UTC, kyle-glick commented on app/views/dashboard/epic_queues/_epic_queue_list.html.haml
> +              Send
Ditto

2017-03-20 16:05 UTC, kyle-glick commented on app/views/protocols/push_to_epic.js.coffee
> +$('.epic-queue-table').bootstrapTable('refresh')
Missing copyright text

2017-03-20 16:23 UTC, wtholt commented on app/helpers/dashboard/epic_queues_helper.rb
> +    "#{identity.try(:first_name)} #{identity.try(:last_name)}"
Oh yeah, nice catch. Forgot about that method.

2017-03-21 20:45 UTC, kayla-glick approved these changes

2017-03-23 18:56 UTC, jleonardw9 approved these changes

2017-03-28 13:52 UTC, Stuart-Johnson approved these changes

2017-03-28 13:52 UTC, merged