Jtm view details reconfig
bmic-development/sparc-request pull request #162
Opened 2017-03-22 19:59 UTC by BigChiefSmidgeums

2017-03-23 15:02 UTC, kayla-glick requested changes

2017-03-23 15:02 UTC, kyle-glick commented on app/controllers/dashboard/protocols_controller.rb
> -  def view_details
I think there was a :view_details symbol in one of the before_filters in this controller. `before_filter find_protocol`. Can you remove it?

2017-03-23 15:02 UTC, kyle-glick commented on spec/controllers/protocols/get_show.rb
> +# Copyright © 2011-2016 MUSC Foundation for Research Development
Minor, but spec should be named get_show_spec.rb

2017-03-23 15:02 UTC, kyle-glick commented on spec/factories/protocol.rb
> +    factory :protocol_study_without_validations, traits: [:without_validations, :study]
Should rename to study_without_validations to be consistent with project_without_validations

2017-03-23 15:02 UTC, kyle-glick commented on spec/factories/protocol.rb
> +    factory :protocol_invalid_study_with_questions, traits: [:without_validations, :study, :with_study_type_questions_group]
See previous comment for naming convention. What makes this invalid? Should that be without_validations?

2017-03-23 15:02 UTC, kyle-glick commented on spec/factories/protocol.rb
> +  factory :study_without_validations, parent: :protocol_study_without_validations, class: 'Study'
Why are you aliasing other factories without new traits?

2017-04-05 15:36 UTC, kayla-glick approved these changes

2017-04-06 19:52 UTC, Stuart-Johnson approved these changes

2017-04-11 11:34 UTC, jwiel86 approved these changes

2017-04-11 14:32 UTC, merged