Wth view epic queue part 2
bmic-development/sparc-request pull request #163
Opened 2017-03-22 20:10 UTC by wtholt

2017-03-23 15:07 UTC, kayla-glick requested changes

2017-03-23 15:07 UTC, kyle-glick commented on app/views/dashboard/epic_queues/_epic_queue_list.html.haml
> +        = link_to 'Past', '#past', data: { toggle: 'tab' }
Needs to be YMLized

2017-03-23 18:39 UTC, jwiel86 approved these changes

2017-03-23 19:19 UTC, jleonardw9 approved these changes

2017-03-27 15:06 UTC, kayla-glick approved these changes

2017-03-28 13:56 UTC, merged