Jtm saved filters refactor
bmic-development/sparc-request pull request #270
Opened 2017-05-16 15:19 UTC by BigChiefSmidgeums

2017-05-17 13:42 UTC, kayla-glick requested changes

2017-05-17 13:42 UTC, kyle-glick commented on app/controllers/dashboard/protocol_filters_controller.rb
> +    @protocol_filters = ProtocolFilter.latest_for_user(@user.id, 15)
We should define "15" as a static value on the ProtocolFilter model since it's used in more than one place.

2017-05-18 14:32 UTC, kayla-glick approved these changes

2017-05-22 14:38 UTC, marklohr approved these changes

2017-05-24 00:50 UTC, Stuart-Johnson approved these changes

2017-05-24 00:50 UTC, merged