Allow disabling of Research Master ID [#136739797]
bmic-development/sparc-request pull request #29
Opened 2017-01-19 15:23 UTC by jayhardee9

2017-01-19 15:33 UTC, wtholt approved these changes

2017-01-20 15:12 UTC, jleonardw9 approved these changes

2017-01-23 15:31 UTC, jwiel86 approved these changes

2017-01-23 15:33 UTC, kayla-glick requested changes

2017-01-23 15:33 UTC, kyle-glick commented on app/views/protocols/form/study_form_sections/_study_information.html.haml
> +    - if RESEARCH_MASTER_ENABLED
This needs to be done also in app/views/dashboard/protocols/form/study_form_sections/_study_information.html.haml

I think there's also code for RMID in app/views/protocols/form/_project_roles_fields.html.haml and the dashboard equivalent. Can you check that too?

2017-01-23 19:34 UTC, merged