wth - Refactor add_service method in
bmic-development/sparc-request pull request #358
Opened 2017-06-26 18:03 UTC by wtholt

app/controllers/service_requests_controller.rb

Refactored add_service method, extracted logic into ruby class.

[#121053875]

Story - https://www.pivotaltracker.com/story/show/121053875

2017-06-26 18:54 UTC, kyle-glick commented on app/controllers/service_requests_controller.rb
> +    add_service = AddService.new(@service_request,
While I think it's good to keep the controller method a bit shorter by extracting to a lib file, I think this needs more work to actually improve upon the existing code. This feels like a band-aid more than a fix.

The biggest problem I've had with this controller action is that it's _really slow_ and there's a lot of extra work being done and poor optimization that needs to be improved.

2017-06-26 19:38 UTC, SamWord requested changes
Why move those private methods to a new lib file? It makes the file look shorter but it might make `add_service` harder to follow if a bug were to arise.  Generally I would make them private methods in the controller with descriptive names.

2017-06-27 00:07 UTC, jleonardw9 commented
@SamWord It's pretty standard practice to refactor fat controllers in Rails using service objects. This is done using a PORO, or Plain Old Ruby Object (class), like Will has done here. Check out this article for more info: http://www.thegreatcodeadventure.com/service-objects-in-rails/

2017-06-27 00:07 UTC, jleonardw9 approved these changes

2017-06-27 11:02 UTC, wtholt commented
@SamWord This is a standard way of refactoring in OOP. 

As this helpful guide states - 

- This refactoring method will help maintain adherence to the Single Responsibility Principle. The code of your classes will be more obvious and understandable.

- Single-responsibility classes are more reliable and tolerant of changes. For example, say that you have a class responsible for ten different things. When you change this class to make it better for one thing, you risk breaking it for the nine others.

Reference - https://sourcemaking.com/refactoring/extract-class

2017-06-27 12:50 UTC, amcates commented
Looks great to me and makes perfect sense to move the logic out to a base class.   Rejecting a pull request should be reserved for when the code doesn't function as it should or would create a bug.  Otherwise, offer up an alternate solution offline.

2017-06-27 13:30 UTC, SamWord approved these changes

2017-06-27 15:22 UTC, closed without merging