KG - Dashboard Visit Groups Controller Specs / Day Validation Bug
bmic-development/sparc-request pull request #8
Opened 2017-01-11 20:29 UTC by kyle-glick

2017-01-12 13:38 UTC, jayhardee9 commented on app/controllers/visit_groups_controller.rb
> +      if @visit_group.day.nil?
I would add a comment explaining what this is doing, since this is a little out of the ordinary.

2017-01-12 13:39 UTC, jayhardee9 requested changes

2017-01-12 13:39 UTC, jayhardee9 commented on config/application.yml.example
> +<<<<<<< HEAD
This needs to be resolved.

2017-01-12 13:39 UTC, jayhardee9 commented on app/controllers/dashboard/visit_groups_controller.rb
> +      flash[:alert] = 'You are not allowed to access that Visit Group.'
This should be localized

2017-01-17 14:19 UTC, wtholt commented on app/controllers/dashboard/visit_groups_controller.rb
> +  before_filter :find_service_request
before_action is new syntax

2017-01-17 14:19 UTC, wtholt commented on app/controllers/dashboard/visit_groups_controller.rb
> +    @visit_group  = VisitGroup.new()
Don't need parenthesis

2017-01-18 16:56 UTC, kyle-glick commented
**NOTE** When this is merged, please also deliver https://www.pivotaltracker.com/story/show/135552501 as requested by Wenjun

2017-01-19 14:41 UTC, merged