wth - (SPARCRequest & SPARCDashboard) Display Research Master ID in
bmic-development/sparc-request pull request #94
Opened 2017-02-16 16:09 UTC by wtholt

"View Study/Project Details" and "Study Summary"

This fixes error where Research Master ID was being displayed in the
Project Summaries on Proper and Dashboard. Only should be on Studies. [#139008535]

2017-02-16 17:21 UTC, jleonardw9 approved these changes

2017-02-16 20:22 UTC, jayhardee9 approved these changes

2017-02-17 12:09 UTC, jwiel86 approved these changes

2017-02-17 14:30 UTC, kayla-glick requested changes

2017-02-17 14:30 UTC, kyle-glick commented on app/views/dashboard/protocols/_summary.html.haml
> +    - if protocol.is_study?
Could do if protocol.is_study? && RESEARCH_MASTER_ENABLED just to be a little more space efficient

2017-02-17 14:30 UTC, kyle-glick commented on app/views/protocols/_summary.html.haml
> +    - if protocol.is_study?
Ditto

2017-02-17 14:50 UTC, wtholt commented on app/views/dashboard/protocols/_summary.html.haml
> +    - if protocol.is_study?
Yeah I agree

2017-02-17 17:36 UTC, kayla-glick approved these changes

2017-02-17 17:37 UTC, Stuart-Johnson approved these changes

2017-02-17 22:17 UTC, merged